In [6]:
import yfinance as yf
import pandas as pd

# Fetch historical data for BTC-USD
data = yf.download("BTC-USD")

# Calculate daily returns
# Daily return = (Today's Close / Yesterday's Close) - 1
data['Daily Return'] = data['Close'].pct_change()

# Remove any rows with NaN values which might be present in the first row
data.dropna(subset=['Daily Return'], inplace=True)

[*********************100%%**********************]  1 of 1 completed

In [7]:
data

,Open,High,Low,Close,Adj Close,Volume,Daily Return
Date,,,,,,,
2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200,-0.071926
2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700,-0.069843
2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600,0.035735
2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100,-0.024659
2014-09-22,399.100006,406.915985,397.130005,402.152008,402.152008,24127600,0.008352
...,...,...,...,...,...,...,...
2024-04-12,70061.382812,71222.742188,65254.835938,67195.867188,67195.867188,44129299406,-0.040889
2024-04-13,67188.375000,67931.429688,60919.105469,63821.472656,63821.472656,52869738185,-0.050217
2024-04-14,63836.230469,65824.429688,62205.851562,65738.726562,65738.726562,49084320047,0.030041
2024-04-15,65739.648438,66878.648438,62332.070312,63426.210938,63426.210938,43595917654,-0.035177
2024-04-16,63441.960938,63825.550781,61763.863281,62699.035156,62699.035156,43217932288,-0.011465

In [26]:
def rm_us(str):
    return str.split(" US")[0]

us_issuances = pd.read_csv('data/Bank US Secondaries.csv')
unique_tickers = list(us_issuances['Issuer Ticker'].apply(rm_us).unique())

data = yf.download(unique_tickers)

[*********************100%%**********************]  168 of 168 completed

57 Failed downloads:
['9191919D', 'FSB', 'MSL', 'FBC', '1368189D', 'TCF', 'ACBI', 'GFED', 'UMPQ', 'SBTB', 'SBBX', 'SSFN', 'IBKC', 'YRKB', 'SBKK', 'MFNC', '9999777D', 'CSFL', 'GWB', '9745633D', 'HBMD', '1965436D', '9966911D', 'CARO', 'SLCT', '1520745D', '1740293D', '8989898D', '9990301D', '2301851D', 'NCOM', 'TCFC', 'OPB', '1935465D', 'TSC', '2370058D', 'BOCH', '1489775D', '0891179D', '9998123D', 'STXB']: Exception('%ticker%: No timezone found, symbol may be delisted')
['SVBA', 'FUBC', 'NPBC', 'COB', 'XBKS', 'BNCN', 'FCTY', 'VGBK', 'TLMR', 'CFIS', 'SNBC', 'WIBC', 'FMTB', 'FSGI', 'SBCP', 'PVTB']: Exception('%ticker%: No price data found, symbol may be delisted (1d 1925-05-10 -> 2024-04-16)')

In [45]:
data['Adj Close']['SIVBQ']

Date
1980-03-17     NaN
1980-03-18     NaN
1980-03-19     NaN
1980-03-20     NaN
1980-03-21     NaN
              ...
2024-04-10    0.05
2024-04-11    0.06
2024-04-12    0.05
2024-04-15    0.06
2024-04-16    0.05
Name: SIVBQ, Length: 11114, dtype: float64