In [1]:
import pandas as pd

In [51]:
bases_df = pd.read_csv("Bank US Secondaries.csv")
bases_df['TICKER'] = bases_df['Issuer Ticker'].str[:-3]
wrds_df = pd.read_csv('wrds_bank2.csv')
wrds_df['MKTCAP'] = wrds_df['SHROUT'] * wrds_df['PRC']/1000

C:\Users\micro\AppData\Local\Temp\ipykernel_9940\2434201817.py:3: DtypeWarning: Columns (6,13,17) have mixed types. Specify dtype option on import or set low_memory=False.
  wrds_df = pd.read_csv('wrds_bank2.csv')

In [63]:
tdf = df[(df['Announced Date'] >= pd.Timestamp('2014-01-01')) & (df['Announced Date'] <= pd.Timestamp('2023-12-31'))]

In [53]:
import pandas as pd

# Convert 'Announced Date' in bases_df and 'date' in wrd_df to datetime objects
bases_df['Announced Date'] = pd.to_datetime(bases_df['Announced Date'])
wrds_df['date'] = pd.to_datetime(wrds_df['date'])

bases_df = bases_df.sort_values('Announced Date')
wrds_df = wrds_df.sort_values('date')

# Perform an asof merge with a tolerance of 7 days
df = pd.merge_asof(bases_df, wrds_df[['date', 'TICKER', 'MKTCAP']],
                   left_on='Announced Date', right_on='date',
                   by='TICKER', tolerance=pd.Timedelta(days=7), direction='nearest')

In [60]:
wrds_df[wrds_df['TICKER'] == 'FRCB']

Empty DataFrame
Columns: [PERMNO, date, TICKER, DLAMT, DLPDT, DLSTCD, NEXTDT, NWPERM, DLRETX, DLPRC, DLRET, PRC, VOL, RET, BID, ASK, SHROUT, RETX, MKTCAP]
Index: []

In [55]:
df[df['MKTCAP'].isnull()]

,Announced Date,Issuer Ticker,Issuer Name,Offer Size (M),Offer Type,Offer Price,Offer To Date,Pricing Date,Expected Pricing Date,Offer Currency,Expect Pricing Message,TICKER,date,MKTCAP
0,2011-01-19,FITB US,Fifth Third Bancorp,1870.0000,"ADDL,Primary Share Offering",14.00,147.285714,1/20/2011,NaN,USD,0,FITB,NaT,NaN
1,2011-02-28,TBBK US,Bancorp Inc/The,57.8737,"ADDL,Primary Share Offering",8.25,286.787879,3/2/2011,NaN,USD,0,TBBK,NaT,NaN
2,2011-03-03,0891179D US,Sterling Bancorp/Old,38.6400,"ADDL,Primary Share Offering",9.60,NaN,3/3/2011,NaN,USD,0,0891179D,NaT,NaN
3,2011-03-07,FISI US,Financial Institutions Inc,45.5102,"ADDL,Primary Share Offering",16.35,1.957187,3/10/2011,NaN,USD,0,FISI,NaT,NaN
4,2011-03-09,9745633D US,TCF Financial Corp/DE,230.0010,"ADDL,Primary Share Offering",15.25,NaN,3/9/2011,NaN,USD,0,9745633D,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2021-12-06,SICP US,Silvergate Capital Corp,552.0000,"ADDL,Primary Share Offering,Accelerated Bookbu...",145.00,NaN,12/6/2021,NaN,USD,0,SICP,NaT,NaN
268,2022-08-01,FRCB US,First Republic Bank/CA,353.2500,"ADDL,Primary Share Offering,Accelerated Bookbuild",157.00,NaN,8/1/2022,NaN,USD,0,FRCB,NaT,NaN
271,2023-02-07,FRCB US,First Republic Bank/CA,402.5000,"ADDL,Primary Share Offering,Accelerated Bookbuild",140.00,NaN,2/8/2023,NaN,USD,0,FRCB,NaT,NaN
272,2023-03-09,SIVBQ US,SVB Financial Group,1250.0000,"ADDL,Accelerated Bookbuild",0.00,NaN,,NaN,USD,TBA,SIVBQ,NaT,NaN
274,2024-03-27,FSBC US,Five Star Bancorp,75.0375,"ADDL,Primary Share Offering,Accelerated Bookbuild",21.75,-1.471264,3/28/2024,NaN,USD,0,FSBC,NaT,NaN

In [38]:
df.to_csv('US_Banks_Shares.csv')

In [39]:
df['weight'] = df['Offer Size (M)'] / df['MKTCAP']

In [40]:
df.sort_values('weight',ascending=False)

,Announced Date,Issuer Ticker,Issuer Name,Offer Size (M),Offer Type,Offer Price,Offer To Date,Pricing Date,Expected Pricing Date,Offer Currency,Expect Pricing Message,wrds_ticker,date,TICKER,MKTCAP,weight
152,2014-01-17,OSBC US,Old Second Bancorp Inc,68.3100,"ADDL,Primary Share Offering",4.40,203.409091,4/3/2014,NaN,USD,0,OSBC,2014-01-17,OSBC,64.57488,1.057842
120,2015-08-03,FFWM US,First Foundation Inc,138.0010,"ADDL,Primary Share Offering,Accelerated Bookbu...",19.25,-32.987013,8/6/2015,NaN,USD,0,FFWM,2015-08-03,FFWM,188.28398,0.732941
131,2015-03-03,HBMD US,Howard Bancorp Inc,24.9998,"ADDL,Primary Share Offering,Best Efforts,Priva...",11.50,NaN,3/3/2015,NaN,USD,0,HBMD,2015-03-03,HBMD,51.41040,0.486279
125,2015-05-04,QCRH US,QCR Holdings Inc,67.1600,"ADDL,Primary Share Offering",18.25,203.890411,5/7/2015,NaN,USD,0,QCRH,2015-05-04,QCRH,143.92800,0.466622
60,2017-03-22,SSFN US,Stewardship Financial Corp,20.7001,"ADDL,Primary Share Offering",8.25,NaN,4/11/2017,NaN,USD,0,SSFN,2017-03-22,SSFN,51.72245,0.400215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,2021-06-03,WAL US,Western Alliance Bancorp,0.0000,"ADDL,Primary Share Offering,Best Efforts,At Th...",0.00,NaN,,NaN,USD,TBA,WAL,2021-06-03,WAL,10531.68550,0.000000
148,2014-03-25,UCBI US,United Community Banks Inc/GA,0.0000,"ADDL,Primary Share Offering,Best Efforts,At Th...",0.00,NaN,,NaN,USD,0,UCBI,2014-03-25,UCBI,972.54960,0.000000
111,2015-11-19,UCBI US,United Community Banks Inc/GA,0.0000,"ADDL,Secondary Share Offering,PE Backed,PE Exit",0.00,NaN,,NaN,USD,0,UCBI,2015-11-19,UCBI,1488.04704,0.000000
118,2015-08-19,MOFG US,MidWestOne Financial Group Inc,0.0000,"ADDL,Secondary Share Offering",0.00,NaN,,NaN,USD,0,MOFG,2015-08-19,MOFG,352.44540,0.000000
142,2014-07-01,CNOB US,ConnectOne Bancorp Inc,44.3438,"ADDL,Secondary Share Offering",18.75,-4.693333,7/7/2014,NaN,USD,0,CNOB,2014-07-01,CNOB,NaN,NaN

In [41]:
df[df['TICKER'] == 'CFIC']

Empty DataFrame
Columns: [Announced Date, Issuer Ticker, Issuer Name, Offer Size (M), Offer Type, Offer Price, Offer To Date, Pricing Date, Expected Pricing Date, Offer Currency, Expect Pricing Message, wrds_ticker, date, TICKER, MKTCAP, weight]
Index: []