# <span style="color:green">Quant Platform</span>

The <span style="color:green">*Quant Platform*</span> is a framework for conducting backtests and analyzing the results that can be easily adapted for live trading. Some components needs to be modified or adapted for each strategy being backtested, others can be left alone.

### Overview of components for <span style="color:green">Quant Platform</span>

<span style="color:blue">Blue</span> components require little to no modification for each strategy tested, while <span style="color:orange">orange</span> components do require modification

1. <span style="color:orange">Data Processor</span>
    - Loads and merges data
    - Provides universe of securities and signals for each date
1. <span style="color:blue">Portfolio</span>
    - Tracks current portfolio and account balance sheet
    - Keeps records of all trades/transactions
    - Keeps history of NAV and margin requirements
1. <span style="color:orange">Trading Rule</span>
    - Decides which trades to make given a universe of securities, signals, and current portfolio
1. <span style="color:blue">Executor</span>
    - "Submits" order either hypothetically using historical data or live to a brokerage
    - Calculates or retrieves transaction prices accounting for any liquidity costs
1. <span style="color:blue">Statistician</span>
    - Looks at results of backtest or live trading and computes statistics ($\alpha$ etc) as well as informative plots (e.g. NAV and margin over time)

### Pseudo-code for backtest

At a high level, our backtest will:

1. Tell the **Data Processor** to load all the necessary data
1. For each unique date in the data:
    1. Get signal  and price data for that date from the **Data Processor**
    1. Tell **Portfolio** to update prices based on new data
    1. Ask **Trading Rule** to decide which trades to make
    1. Tell **Executor** to execute the trades
    1. Update **Portfolio** to reflect the executed trades
1. Tell **Statistician** to summarize the results

In [1]:
# Imports
from IPython.display import display, Markdown, Latex, clear_output
import numpy as np
import pandas as pd

In [2]:
from IPython.display import display, HTML
display(HTML("<style>.jp-OutputArea-output {max-height: 10000000000000px; }</style>"))

In [3]:
# Step 1: "Run" the notebooks containing definitions of the specifics of the data, strategy, and post-test statistics we want to compute
# Think about this as importing these tools but not using them yet

# These tools should be changed depending on the strategy you are testing
%run sbf_data_processor.ipynb
%run sbf_trading_rule.ipynb

# # These tools should remain unchanged across strategies unless you have a good reason to change them
%run portfolio_db.ipynb
%run backtest_executor.ipynb # if you were live trading a strategy, this would be replace by code that submitted orders etc

In [4]:
# Step 2: Create the tools we'll need to do the backtest
# These can be customized and changed while keeping the rest of this file (the backtest logic) the same

# DO edit this code to make sure that the specifics tools you want for this backtest are chosen here

# DO NOT edit the names of the variables, only what's assigned to them. So 
# good: data_processor = MyNewDataProcessor() 
# bad: my_new_data_processor = MyNewDataProcessor()

# Data processor, in charge of loading and doling out data
data_processor = SBFDataProcessor()

In [5]:
# Portfolio database, keeps track of all the trades the backtest makes, the strategy NAV, and the current portfolio as we go through the backtest
%run portfolio_db.ipynb
portfolio_db = PortfolioDB()

# Strategy logic, in charge of choosing trades based on current portfolio and data
# This exact code would be used for live trading 
trading_rule = SBFTradingRule(portfolio_db)

# Trade executor, in charge of "executing" trades the strategy decides on, turning them into transactions and updating the portfolio
trade_executor = BacktestExecutor(portfolio_db)

# Info about the strategy, used for ex-post statistics and output not the actual backtest
strategy_info = {
    'brief descriptor': 'sbf_ew', 
    'plot descriptor': 'Long Bitcoin, Short Banks who Issue Stock, Equal-Weighted',
    'universe': 'Banking US Equities and Bitcoin',
    'signals': 'Banking Secondary Equity Issuances',
    'trading rule': 'Buy X% (currently 5) of NAV in Bitcoin when Bank issues stock, Short X% (currently 5) of Underlying Bank Stock',
    'holding period': 'Two months (can be altered in constants.py)',
    'periods per year': 252, 
    'time lag': '0', #We trade on the annoucement of the secondary equity issuance which should be immediate
    'output folder name': 'output'
}

# Statistician, used to tabulate and plot statistics after the backtest runs
%run backtest_statistician.ipynb
statistican = BacktestStatistican(portfolio_db,strategy_info)

In [6]:
# Step 3: Run actual backtest
# Do NOT edit this cell without a very good reason

# Add 100 initial cash to our portfolios
portfolio_db.add_cash(100)

# Get our list of unique dates
udates = data_processor.unique_dates()

# Main loop for the backtest
for date in udates:
    print(date)
    # dataframes for the date
    signal_df = data_processor.signal_df_for_date(date)
    price_df = data_processor.price_df_for_date(date)

    # Update prices to reflect the new values after however much time has passed
    # Need to dot his first each date because the updated prices may affect our trading rule
    
    print("we are here")
    portfolio_db.update_prices(price_df)
    
    # Ask the trading rule what trades we should make
    open_trades_df, close_trades_df = trading_rule.compute_trades(signal_df=signal_df, date=date)

    # apply dates to trades
    open_trades_df['open_datetime'] = date
    close_trades_df['close_datetime'] = date

    # execute trades
    trade_executor.execute_opens(open_trades_df=open_trades_df, price_df=price_df)
    trade_executor.execute_closes(close_trades_df=close_trades_df, price_df=price_df)    
    
    # Record account data for today
    portfolio_db.record_account_data(price_df=price_df,datetime=date)
    
    # Do some fancy output tracking our NAV and margin requirement each day
    
    display( np.datetime_as_string(np.datetime64(date), unit='D') + ': ' + str(portfolio_db.current_nav()) + " | " + str(portfolio_db.current_margin()))
    
    
    if len(signal_df) > 2:
        #break
        clear_output(wait=True)
        pass
    else:
        clear_output(wait=True)

# Now that the loop is done, tell the statistican to output stats
statistican.output_stats()

2016-05-25 00:00:00
we are here

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [ ]:
open_trades_df

In [ ]:
close_trades_df

In [16]:
portfolio_db.trades_df.loc[:,'close_datetime'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
142     True
143     True
144     True
145     True
146     True
Name: close_datetime, Length: 147, dtype: bool

In [21]:
portfolio_db.trades_df

,quantity,open_average_price,close_datetime,close_average_price,size,security_id,open_datetime,quantity_multiple
0,0.109567,411.574005,2014-10-09,365.026001,NaN,BTC-USD,2014-09-25,1.000000
1,-8.213793,4.564840,2014-10-09,4.371470,NaN,TSB LN,2014-09-25,NaN
2,0.104605,386.944000,2014-10-14,400.869995,NaN,BTC-USD,2014-09-30,1.000000
3,-9.243424,4.087270,2014-10-14,3.899090,NaN,NWG LN,2014-09-30,NaN
4,0.128729,358.416992,2014-11-06,349.290009,NaN,BTC-USD,2014-10-23,1.000000
...,...,...,...,...,...,...,...,...
142,0.159393,445.980988,NaT,NaN,NaN,BTC-USD,2016-05-24,1.000000
143,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,1.000000
144,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739
145,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,1.000000
146,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739

In [22]:
portfolio_db.positions_df

,security_id,quantity,average_cost,current_price,quantity_multiple,prc,ret,lagged_price
0,BTC-USD,0.159393,445.980988,449.598999,1.000000,449.598999,0.008112,445.980988
1,INBK US,-6.041451,23.532900,24.726200,1.000000,24.726200,0.050708,23.532900
2,INBK US,-5.749887,23.532900,24.726200,0.951739,24.726200,0.000000,23.532900
3,INBK US,-6.041451,23.532900,24.726200,1.000000,24.726200,0.050708,23.532900
4,INBK US,-5.749887,23.532900,24.726200,0.951739,24.726200,0.000000,23.532900
5,cash,248.802505,1.000000,1.000000,1.000000,NaN,0.000000,1.000000

In [39]:
portfolio_db.trades_df

,quantity,open_average_price,close_datetime,close_average_price,size,security_id,open_datetime,quantity_multiple
0,0.109567,411.574005,2014-10-09,365.026001,NaN,BTC-USD,2014-09-25,1.000000
1,-8.213793,4.564840,2014-10-09,4.371470,NaN,TSB LN,2014-09-25,NaN
2,0.104605,386.944000,2014-10-14,400.869995,NaN,BTC-USD,2014-09-30,1.000000
3,-9.243424,4.087270,2014-10-14,3.899090,NaN,NWG LN,2014-09-30,NaN
4,0.128729,358.416992,2014-11-06,349.290009,NaN,BTC-USD,2014-10-23,1.000000
...,...,...,...,...,...,...,...,...
142,0.159393,445.980988,NaT,NaN,NaN,BTC-USD,2016-05-24,1.000000
143,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,1.000000
144,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739
145,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,1.000000
146,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739

In [42]:
tdf = portfolio_db.trades_df.merge(portfolio_db.positions_df.loc[:, ['security_id', 'quantity_multiple']],
                                   on='security_id',
                                   suffixes=('', '_posdf'),
                                   how='left',
                                   indicator=True)

In [43]:
tdf

,quantity,open_average_price,close_datetime,close_average_price,size,security_id,open_datetime,quantity_multiple,quantity_multiple_posdf,_merge
0,0.109567,411.574005,2014-10-09,365.026001,NaN,BTC-USD,2014-09-25,1.000000,1.000000,both
1,-8.213793,4.564840,2014-10-09,4.371470,NaN,TSB LN,2014-09-25,NaN,NaN,left_only
2,0.104605,386.944000,2014-10-14,400.869995,NaN,BTC-USD,2014-09-30,1.000000,1.000000,both
3,-9.243424,4.087270,2014-10-14,3.899090,NaN,NWG LN,2014-09-30,NaN,NaN,left_only
4,0.128729,358.416992,2014-11-06,349.290009,NaN,BTC-USD,2014-10-23,1.000000,1.000000,both
...,...,...,...,...,...,...,...,...,...,...
166,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,1.000000,0.951739,both
167,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739,1.000000,both
168,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739,0.951739,both
169,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739,1.000000,both
170,-6.041451,23.532900,NaT,NaN,NaN,INBK US,2016-05-24,0.951739,0.951739,both

In [23]:
portfolio_db.trades_df.loc[:,'close_datetime'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
142     True
143     True
144     True
145     True
146     True
Name: close_datetime, Length: 147, dtype: bool